### ISSUE TITLE
Find feature doesn't allow pasting

### ISSUE THREAD

**Issue by dandrejvv** [IntentSoftware/Intent.Modules#113]
The new find text box is useful when you type something in to look for however, it would be great to be able to paste text in it as well for it to search.

**Comment by garethbaars** [comment]
Hi @dandrejvv, this is a bug. We will fix this for the next release

**Comment by dandrejvv** [comment]
@garethbaars any update on this? Still not in 1.5.1 of Intent

**Comment by dandrejvv** [comment]
This has been resolved in Intent Architect 2.1.x
