### ISSUE TITLE
Intent.Application.Contracts.Mappings is tech specific

### ISSUE THREAD

**Issue by dandrejvv** [IntentSoftware/Intent.Modules#133]
The module `Intent.Application.Contracts.Mappings` uses Automapper inside to do DTO to Domain (and vice-versa) mappings. People may not want to use Automapper so potentially I think it might need to be renamed and an Automapper Interop should be added.

Would you agree? (Provided the Mapping tech in Intent doesn't solely rely on Automapper being used)

**Comment by garethbaars** [comment]
Agreed. This module should include the `AutoMapper` name (e.g. `Intent.Application.Contracts.Mappings.Automapper')

**Comment by dandrejvv** [comment]
This module has already been adapted to include Automapper in the title
