### ISSUE TITLE
Linux / Ubuntu Support

### ISSUE THREAD

**Issue by laredoza** [IntentSoftware/Intent.Modules#194]
Hi,

Is there any support for Ubuntu / Linux for the UI?

Regards

**Comment by JonathanLydall** [comment]
Hi @laredoza,

Not yet, but Intent Architect already works on macOS so we don't expect it being hard to add support for Ubuntu as well.

**Comment by laredoza** [comment]
Thanks, looking forward to the Linux version. 

Please contact me if you need a guinea pig.

**Comment by laredoza** [comment]
My apologies for only getting back to you now. LTS would be perfect for me. I'm currently using Linux Mint 20.1 which is based on Ubuntu 20.04 LTS.

**Comment by JonathanLydall** [comment]
@laredoza, we now have a pre-release version available which is also built for Linux on our [download page](https://intentarchitect.com/#/downloads).

The recommended and default installer type for Linux is .AppImage as it allows automatic updating to work while for .deb and .rpm you would need to manually download and install updates.

In case you're not familiar with using an AppImage, running them is [as simple as marking them as executable](https://docs.appimage.org/introduction/quickstart.html#how-to-run-an-appimage), but if you want to have them integrate a little more with the desktop (for example showing under your applications), it's also quite easy to [install support for your Linux distribution](https://docs.appimage.org/user-guide/run-appimages.html#integrating-appimages-into-the-desktop) which does this.
