### ISSUE TITLE
Contructor Generating With Odd Fomatting

### ISSUE THREAD

**Issue by Carbz22** [IntentSoftware/Intent.Modules#20]
New constructors seem to be generating with the incorrect format. Beneath is a screen snip with an artistically drawn circle to elaborate.

![anotherintentbugsigh](https://user-images.githubusercontent.com/8687460/30540926-66240788-9c79-11e7-9317-913c9ae05c95.PNG)

**Comment by dandrejvv** [comment]
Lots of improvements and fixes have been made to the Intent Architect modules since then. I presume this is no longer a concern.
