### ISSUE TITLE
DTOs / Services - Collapse/Expand All

### ISSUE THREAD

**Issue by CraigForbes** [IntentSoftware/Intent.Modules#26]
When you open the DTOs view, all folders are currently expanded and you need to scroll to navigate and collapse each folder individually, it would be cool if they started collapsed and maybe have an option to expand/collapse all (potentially by the save button?)

![image](https://user-images.githubusercontent.com/17470616/30956285-1a9dfeb6-a437-11e7-9438-47709386e4b1.png)

**Comment by dandrejvv** [comment]
Can we add this for the next release? This is becoming a very much sought after feature for both the Services and Domain designer in their respective tree views.

**Comment by dandrejvv** [comment]
This has been finally addressed in Intent Architect 2.1.x where you can collapse and expand tree view nodes
