### ISSUE TITLE
Spam Clicking DTOs Issue

### ISSUE THREAD

**Issue by Carbz22** [IntentSoftware/Intent.Modules#27]
Spam clicking dto's or services causes the popups seen in the second screenshot to show up. It then picks up changes when navigate from either services or dto's. If you click yes it will delete all the packages for that section.

![image](https://user-images.githubusercontent.com/8687460/30966556-9b855462-a459-11e7-9463-ae42d9ae6ad4.png)
![image](https://user-images.githubusercontent.com/8687460/30966578-b010139a-a459-11e7-8583-c5855416bcf6.png)

**Comment by dandrejvv** [comment]
Testing on Intent Architect 2.1.3 (since we've made lots of improvements and bug fixes in the mean time), I've tried spam clicking the exact same button on the same page and I was not able to replicate this error.
