### ISSUE TITLE
RichDomain Module - Behaviour operations and classes don't respect abstract from model

### ISSUE THREAD

**Issue by JonathanLydall** [IntentSoftware/Intent.Modules#29]
In the domain model, set a class as abstract and add an abstract command operation.

Observe that the abstract is ignored on the code gen for the Behaviour class.

**Comment by dandrejvv** [comment]
I am aware of an `Is Abstract` flag on an operation so I assume you meant that as the "abstract command operation". I've tested this in the current version and it is behaving as expected.
