### ISSUE TITLE
Domain Modeller - Self referencing associations

### ISSUE THREAD

**Issue by joelsteventurner** [IntentSoftware/Intent.Modules#31]
If you create an Entity and Add a Self Referencing association, by clicking on the Domain object twice, you can not see or manipulate the association in the Editor.

Click Association, Click on the Domain entity twice. 

You can see the relationship in the tree view but its not visible in the UML Model

**Comment by dandrejvv** [comment]
Self referencing associations have been working since Intent Architect 1.8/9 so it might have been fixed in the mean time

**Comment by JonathanLydall** [comment]
Yes, I just checked and it seems it's not possible to have self-referencing associations become invisible anymore.
