### ISSUE TITLE
DTOs - Mappings - Doesn't show fields from inherited class

### ISSUE THREAD

**Issue by JonathanLydall** [IntentSoftware/Intent.Modules#32]
Don't get an option to map operations.

Doesn't show mappable fields from parent classes.

**Comment by dandrejvv** [comment]
Since Intent Architect 2.x / 3.0 a lot of enhancements were made to the mapping system that would allow one to view Entity associations (including inheritance) and be able to map from parent classes/entities.

**Comment by JonathanLydall** [comment]
This is about being able to select an operation to map from, which isn't possible still:
![image](https://user-images.githubusercontent.com/1290262/126511205-1a232e67-c36b-4231-9d9c-f63441058608.png)

**Comment by garethbaars** [comment]
This is in fact working. In the Services Designer, the operation has to return a type, and not accept parameters for it to be mappable.
![image](https://user-images.githubusercontent.com/11704575/126524105-647ea7d1-f7ad-4cf4-a9fa-a7c2423784fc.png)
