### ISSUE TITLE
Dialog visual issue

### ISSUE THREAD

**Issue by Carbz22** [IntentSoftware/Intent.Modules#33]
The no (negative condition) button has focus when the view loads. It looks a little tacky.

![image](https://user-images.githubusercontent.com/8687460/31496461-b6e2183c-af5b-11e7-91e6-4d83d15ebc6d.png)

**Comment by dandrejvv** [comment]
Since Intent Architect 3.0 this dialog no longer appears when an Intent Application is missing. There is a different way that it deals with missing Applications now, so I suppose the button focus on this dialog is no longer a concern.
