### ISSUE TITLE
Intent.VisualStudio.Projects Module - Not normalizing namespaces for .csproj source entries (also possibly causing duplicate entries)

### ISSUE THREAD

**Issue by JonathanLydall** [IntentSoftware/Intent.Modules#45]
Sometimes the computed file name from a template has two back-slashes in a row and then in the Intent Software Factory Changes screen and .csproj files land up with entries with double slashes:
```
    <Compile Include="Controllers\Generated\\BbbeeManagementServiceController.cs">
      <IntentGenerated>MasterData</IntentGenerated>
      <IntentGenType>RoslynWeave</IntentGenType>
    </Compile>
```

We also have found duplicate entries of sources, it's hard to be sure if it's intent or merging though, but in the same .csproj file you might find:
```
    <Compile Include="Controllers\Generated\BbbeeManagementServiceController.cs" />
    <Compile Include="Controllers\Generated\\BbbeeManagementServiceController.cs">
      <IntentGenerated>MasterData</IntentGenerated>
      <IntentGenType>RoslynWeave</IntentGenType>
    </Compile>
```

I'm not certain it's Intent, but it's possible it's that it thinks it needs to add the entry as it did not match due to the double slash.

**Comment by dandrejvv** [comment]
@JonathanLydall , is this a concern that you've run into until recently? I think this can be closed since I have not encountered this in the last few years using Intent Architect and we've also made tons of updates to address issues like these.

**Comment by JonathanLydall** [comment]
Haven't noticed it either in a very long time, I might have fixed it myself, happy to close it.
