### ISSUE TITLE
IModSpec XML Schema?

### ISSUE THREAD

**Issue by dandrejvv** [IntentSoftware/Intent.Modules#48]
What are your thoughts on having an XSD that gives the developer intellisense on creating and updating ".imodspec" files? It can also provide documentation on how to use certain nodes while working.

**Comment by garethbaars** [comment]
Totally agree. We will look into creating one.

**Comment by dandrejvv** [comment]
Since we developed the Module Builder in Intent Architect which automatically updates the `imodspec` files, there was little need for an XSD schema file.
