### ISSUE TITLE
Linking Modules, Services and DTOs to Projects

### ISSUE THREAD

**Issue by dandrejvv** [IntentSoftware/Intent.Modules#54]
We had the discussion before of having the capability to have a Module being reused on producing the same output on different Projects within the same Intent Application. But that opens up the problem of being able to filter which Services and DTOs need to be associated with Projects as well.
I think the Roles concept is not sufficient for these scenarios. 

So for the time being, I can use the workaround to create multiple roles to assign to different Projects and Stereotypes to different Services and DTOs in order to filter which models go where.

So I think that by keeping the Roles for Modules except allowing one to apply multiple Roles to an Intent Application will solve the Modules problem.
I also think that one thing that might work well is to have some tagging concept be applied to `Folders` and `Models` that are then assigned to `Projects`. (I haven't dabbled with Domain just yet so forgive me if it might fall over at that point)

![image](https://user-images.githubusercontent.com/7236289/34031750-7c2856b4-e17b-11e7-8164-cc5c3b46fc3c.png)
Link these concept groups to my Services

![image](https://user-images.githubusercontent.com/7236289/34031755-7eeb8a1a-e17b-11e7-8e67-812d333c0393.png)
Link these concept groups to my DTOs

![image](https://user-images.githubusercontent.com/7236289/34031745-78e0c04a-e17b-11e7-8296-a2458e896357.png)
Link these concept groups to my Projects

But allow that the DTOs, Services and Project have multiple instances of these concept groups. That way I can have two different Web Service Hosts, host their own services implementations but the data contracts can be stored in the same Library project, for instance.

What are your thoughts?

**Comment by garethbaars** [comment]
Hi @dandrejvv, @joelsteventurner, 

As of 1.3-beta, the new Template Registration system supports the ability to register a template against a specific Project programmatically through the `ITemplateInstanceRegistry` interface.

Does this solve the above use case?

**Comment by dandrejvv** [comment]
I'm closing this issue since the concern that I wanted to address back then has been addressed but it was not the right paradigm for Intent Architect however, it also wasn't a problem per-say since we could make specific modules to generate the projects needed for that solution. Also, Intent Architect 3.0 now has richer abilities in specifying where output gets generated on a project level
