### ISSUE TITLE
Change the Software Factory's console output to use a fixed width font

### ISSUE THREAD

**Issue by JonathanLydall** [IntentSoftware/Intent.Modules#66]
This would make it easier to view multi line entries and would also allow aligning output across multiple lines.

I also personally find it easier to read diagnostic info in a fixed width font.

**Comment by dandrejvv** [comment]
I think with all the enhancements that we've already made (and are still making) this will no longer be a concern?

**Comment by JonathanLydall** [comment]
Happy to close this. With line breaks now visible, this has not been a problem for me.
