### ISSUE TITLE
Slow-cheetah like XML transforms for XML Decorators

### ISSUE THREAD

**Issue by dandrejvv** [IntentSoftware/Intent.Modules#83]
Creating XML Decorators for the VS Project Module to update the Web.config is a cool idea but in code it can be quite a mission to do, especially if you have a lot of custom config to do.
I don't know how worth while it is to do or whether it is possible at this point but I'm putting it out there...

Would it be possible to add some Slow-cheetah like XML transforms to update XML files like for XML Decorators?

**Comment by joelsteventurner** [comment]
It's definitely possible, I wrote a system to do that in a much earlier version of the tool. I basically wrote a factory extension, which would add slow cheetah transforms for xml files. If you have a clear picture of what you want to do I can probably help get something up and running.

**Comment by dandrejvv** [comment]
Oh man @joelsteventurner, I should have asked for it sooner. I wrote a Decorator that adds a lot of custom config to web.config of existing or newly created hosts. Its to check if certain sections are absent and then to add them in a certain way if they are.
I would like to know how to do something like that for future reference.

**Comment by dandrejvv** [comment]
There are decorators in the Intent Architect module set that allows for simpler XML editing when developing modules for Intent Architect applications. So editing Web/App.config files are simpler to do using the XDoc code API
