### ISSUE TITLE
Getting 'System.Runtime.InteropServices.RuntimeInformation' Exception on SF Run

### ISSUE THREAD

**Issue by dandrejvv** [IntentSoftware/Intent.Modules#88]
Using version 1.3.0-beta and the following modules we get the following error when running the Software Factory Run process...

Modules:
 - Intent.Application.Contracts
 - Intent.Application.ServiceCallHandlers
 - Intent.Common
 - Intent.Common.Types
 - Intent.EntityFramework
 - Intent.EntityFramework.Migrations
 - Intent.OutputManager.RoslynWeaver
 - Intent.RichDomain
 - Intent.VisualStudio.Projects

Error:

Executing template :   Intent.VisualStudio.Projects.VisualStudio2015Solution (Auditing.sln)
--
  | Executing template :   Intent.Application.Contracts.ServiceContract (IQueryAuditService.cs)
  | Executing template :   Intent.Application.Contracts.ServiceContract (IAuditPublisherService.cs)
  | Executing template : Intent.Application.Contracts.DTO   (GetAuditByCriteriaRequest.cs)
  | Executing template : Intent.Application.Contracts.DTO   (AuditEntry.cs)
  | Executing template : Intent.Application.Contracts.DTO   (GetAuditByCriteriaResponse.cs)
  | Executing template : Intent.Application.Contracts.DTO   (PublishAuditRequest.cs)
  | Executing template :   Intent.VisualStudio.Projects.NuGetPackagesConfig (packages.config)
  | Executing template :   Intent.VisualStudio.Projects.LibraryCSProjectFile   (Sasfin.Auditing.Contracts.csproj)
  | ManifestLoader : Cant find assembly :   System.Runtime.InteropServices.RuntimeInformation, Version=4.0.1.0,   Culture=neutral, PublicKeyToken=b03f5f7f11d50a3a
  **| Could not load file or assembly   'System.Runtime.InteropServices.RuntimeInformation, Version=4.0.1.0,   Culture=neutral, PublicKeyToken=b03f5f7f11d50a3a' or one of its dependencies.   The system cannot find the file specified.**
  | at Microsoft.Build.Shared.NativeMethodsShared.get_IsLinux() at   Microsoft.Build.Shared.NativeMethodsShared..cctor()

**Comment by JonathanLydall** [comment]
We need to fix the dependencies of the `Intent.VisualStudio.Projects` module. In the meantime though, one can install the NuGet module.

**Comment by dandrejvv** [comment]
Thanks @JonathanLydall it seemed to get passed that exception and we're able to run the code gen from that point on

**Comment by dandrejvv** [comment]
This hasn't been an issue in years. Closing.
