### ISSUE TITLE
The tools version "15.0" is unrecognized. Available tools versions are "2.0", "3.5", "4.0".

### ISSUE THREAD

**Issue by JonathanLydall** [IntentSoftware/Intent.Modules#93]
![image](https://user-images.githubusercontent.com/1290262/35743330-f9970596-0845-11e8-9c21-be48dd0cdf24.png)

This seems to relate to https://github.com/dotnet/roslyn/issues/21583 / https://github.com/Microsoft/msbuild/issues/2369.

We need to see if we can workaround it, upgrading or downgrading MSBuild package may be required.

**Comment by dandrejvv** [comment]
This issue has not happened since Intent Architect 2.x. Not sure if the move to .NET core managed to fix this. Wouldn't you agree @JonathanLydall ?

**Comment by JonathanLydall** [comment]
Happy to close this. Looks like it's actually NuGet related and we've already decided to no longer support "old" NuGet with `packages.config` anymore for reasons like this.
