### ISSUE TITLE
Intent.VisualStudio.Projects.VisualStudio2015Solution template is including `Folder Based Project` in its output

### ISSUE THREAD

**Issue by JonathanLydall** [IntentSoftware/Intent.Modules#96]
![image](https://user-images.githubusercontent.com/1290262/35803509-b0ff0df4-0a7c-11e8-9758-8e91fc57eaa2.png)

![image](https://user-images.githubusercontent.com/1290262/35803533-ca68db6c-0a7c-11e8-8f76-a51e482473ed.png)

**Comment by dandrejvv** [comment]
This issue is certainly no longer a problem. Since Intent Architect 3.0 proper support for Folders has been given for all kinds of project language types
